all:
    hosts:
        test_machine:
            ansible_ssh_host: "192.168.1.210"
            ansible_ssh_private_key_file: "./.ssh/id_rsa"
            ansible_ssh_public_key_file: "./.ssh/id_rsa.pub"
            ansible_user: "student"
